"""Runtime configuration, read once from environment variables."""
import os
from dataclasses import dataclass, field


def _csv(value: str) -> list[str]:
    return [v.strip() for v in value.split(",") if v.strip()]


@dataclass(frozen=True)
class Settings:
    database_url: str = os.getenv("DATABASE_URL", "sqlite:///./fireflies.db")
    cors_origins: list[str] = field(
        default_factory=lambda: _csv(os.getenv("CORS_ORIGINS", "http://localhost:3000"))
    )
    # e.g. "https://.*\.vercel\.app" to allow Vercel preview deployments
    cors_origin_regex: str | None = os.getenv("CORS_ORIGIN_REGEX") or None
    # Optional: when set, summaries and Ask answers are generated by Claude.
    anthropic_api_key: str | None = os.getenv("ANTHROPIC_API_KEY") or None
    llm_model: str = os.getenv("LLM_MODEL", "claude-haiku-4-5-20251001")
    seed_on_startup: bool = os.getenv("SEED_ON_STARTUP", "true").lower() == "true"


settings = Settings()
