"use client";

import { Check, Pencil, PlayCircle, RefreshCw, Sparkles, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { useToast } from "@/components/ui/Toast";
import { api } from "@/lib/api";
import { clock } from "@/lib/format";
import type { ActionItem, MeetingDetail } from "@/lib/types";
import { ActionItems } from "./ActionItems";

function Section({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) {
  return (
    <section className="border-b border-line px-5 py-5 last:border-b-0">
      <div className="mb-3 flex items-center justify-between gap-2">
        <h3 className="text-[15px] font-semibold text-ink">{title}</h3>
        {action}
      </div>
      {children}
    </section>
  );
}

const SOURCE_LABEL: Record<string, string> = { llm: "Generated by Claude", heuristic: "Auto-generated", seed: "AI notes", manual: "Edited" };

export function SummaryPanel({ meeting, onMeeting, onSeek, activeChapterId }: {
  meeting: MeetingDetail; onMeeting: (m: MeetingDetail) => void; onSeek: (ms: number) => void; activeChapterId: number | null;
}) {
  const toast = useToast();
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState("");
  const [regenerating, setRegenerating] = useState(false);
  const s = meeting.summary;

  const saveOverview = async () => {
    try {
      const summary = await api.updateSummary(meeting.id, { overview: draft.trim() });
      onMeeting({ ...meeting, summary });
      setEditing(false);
      toast("Overview saved");
    } catch (e) { toast((e as Error).message, "error"); }
  };

  const regenerate = async () => {
    setRegenerating(true);
    try {
      onMeeting(await api.regenerateSummary(meeting.id));
      toast("Notes regenerated from the transcript");
    } catch (e) { toast((e as Error).message, "error"); }
    finally { setRegenerating(false); }
  };

  const setItems = (action_items: ActionItem[]) => onMeeting({ ...meeting, action_items });

  return (
    <div>
      {s ? (
        <>
          <div className="flex items-center justify-between gap-2 px-5 pt-4">
            <span className="inline-flex items-center gap-1.5 text-xs font-medium text-brand-ink"><Sparkles size={14} /> {SOURCE_LABEL[s.generated_by] ?? "AI notes"}</span>
            {meeting.segments.length > 0 && (
              <button className="btn-ghost h-7 text-xs" onClick={regenerate} disabled={regenerating}>
                <RefreshCw size={13} className={regenerating ? "animate-spin" : ""} /> {regenerating ? "Regenerating…" : "Regenerate"}
              </button>
            )}
          </div>

          {s.keywords.length > 0 && (
            <Section title="Keywords">
              <div className="flex flex-wrap gap-1.5">
                {s.keywords.map((k) => <span key={k} className="chip border border-line bg-surface text-ink">{k}</span>)}
              </div>
            </Section>
          )}

          <Section title="Overview" action={!editing && (
            <button className="btn-ghost h-7 w-7 px-0" onClick={() => { setDraft(s.overview); setEditing(true); }} aria-label="Edit overview"><Pencil size={14} /></button>
          )}>
            {editing ? (
              <div className="space-y-2">
                <textarea className="textarea min-h-[140px] text-sm" value={draft} onChange={(e) => setDraft(e.target.value)} autoFocus aria-label="Overview" />
                <div className="flex justify-end gap-2">
                  <button className="btn-ghost h-8" onClick={() => setEditing(false)}><X size={14} /> Cancel</button>
                  <button className="btn-primary h-8" onClick={saveOverview}><Check size={14} /> Save</button>
                </div>
              </div>
            ) : (
              <p className="text-[14px] leading-[1.65] text-ink/90">{s.overview || "No overview yet."}</p>
            )}
          </Section>
        </>
      ) : (
        <div className="px-5 py-6">
          <p className="text-sm text-muted">No AI notes yet. {meeting.segments.length ? "Generate them from the transcript." : "Add a transcript to generate notes."}</p>
          {meeting.segments.length > 0 && (
            <button className="btn-primary mt-3" onClick={regenerate} disabled={regenerating}><Sparkles size={15} /> {regenerating ? "Generating…" : "Generate notes"}</button>
          )}
        </div>
      )}

      <Section title="Action items">
        <ActionItems meetingId={meeting.id} items={meeting.action_items} people={meeting.participants} onChange={setItems} onSeek={onSeek} />
      </Section>

      {meeting.chapters.length > 0 && (
        <Section title="Outline">
          <ol className="relative space-y-1 before:absolute before:bottom-3 before:left-[7px] before:top-3 before:w-px before:bg-line">
            {meeting.chapters.map((c) => {
              const active = c.id === activeChapterId;
              return (
                <li key={c.id}>
                  <button onClick={() => onSeek(c.start_ms)} className={`relative flex w-full gap-3 rounded-lg py-2 pl-0 pr-2 text-left hover:bg-raised ${active ? "bg-brand-soft/60" : ""}`}>
                    <span className={`relative z-10 mt-1 h-[15px] w-[15px] shrink-0 rounded-full border-2 ${active ? "border-brand bg-brand" : "border-line bg-surface"}`} />
                    <span className="min-w-0">
                      <span className="flex items-baseline gap-2">
                        <span className="text-[14px] font-medium text-ink">{c.title}</span>
                        <span className="inline-flex items-center gap-0.5 text-xs tabular-nums text-brand-ink"><PlayCircle size={11} />{clock(c.start_ms)}</span>
                      </span>
                      {c.summary && <span className="mt-0.5 block text-[13px] leading-snug text-muted">{c.summary}</span>}
                    </span>
                  </button>
                </li>
              );
            })}
          </ol>
        </Section>
      )}
    </div>
  );
}
